name: Run CI/CD Check

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java 11+
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Use a specific Java version
        distribution: 'temurin' # Use Eclipse Temurin distribution (commonly used)

    # Step 3: Run the JAR file
    - name: Run ci-cd-check.jar
      run: java -jar path/to/ci-cd-check.jar
